"""HTTP API over the RAG pipeline.

Run:  uvicorn filinglens.api:app --reload
Docs: http://localhost:8000/docs  (interactive, generated by FastAPI)

Endpoints:
- POST /ask     — cited answer (what the future React UI calls)
- GET  /search  — raw retrieval hits with scores (debugging / "show sources")
- GET  /health  — status + indexed chunk count

The embedding model, Chroma collection, and LLM client are created once
(lru_cache) instead of per request — model loading takes seconds, requests
should take milliseconds. Tests override the dependency functions with
fakes, so the real model/DB/Ollama are never touched in the test suite.
"""

from __future__ import annotations

from functools import lru_cache

from fastapi import Depends, FastAPI, Query
from pydantic import BaseModel, Field

from filinglens.answer import answer_question
from filinglens.retrieve import retrieve

app = FastAPI(title="FilingLens", description="SEC filing Q&A with verifiable citations")


# --- singletons (overridden in tests via app.dependency_overrides) ---------

@lru_cache
def get_embedder():
    from filinglens.embed import LocalEmbedder

    return LocalEmbedder()


@lru_cache
def get_chroma():
    from filinglens.embed import get_collection

    return get_collection()


@lru_cache
def get_llm():
    from filinglens.answer import OllamaLLM

    return OllamaLLM()


# --- request/response shapes ------------------------------------------------

class AskRequest(BaseModel):
    question: str = Field(min_length=3, examples=["What are Apple's supply chain risks?"])
    ticker: str | None = None
    year: str | None = None
    k: int = Field(default=6, ge=1, le=20)


class CitationOut(BaseModel):
    marker: int
    chunk_id: str
    ticker: str
    fiscal_year: str
    item: str
    item_title: str
    char_start: int
    char_end: int
    source_url: str


class AskResponse(BaseModel):
    question: str
    answer: str
    citations: list[CitationOut]


class HitOut(BaseModel):
    id: str
    score: float
    ticker: str
    fiscal_year: str
    item: str
    item_title: str
    text: str
    source_url: str


# --- endpoints ---------------------------------------------------------------

@app.get("/health")
def health(collection=Depends(get_chroma)):
    return {"status": "ok", "chunks": collection.count()}


@app.post("/ask", response_model=AskResponse)
def ask(
    req: AskRequest,
    embedder=Depends(get_embedder),
    collection=Depends(get_chroma),
    llm=Depends(get_llm),
):
    result = answer_question(
        req.question,
        k=req.k,
        ticker=req.ticker,
        year=req.year,
        llm=llm,
        embedder=embedder,
        collection=collection,
    )
    return AskResponse(
        question=result.question,
        answer=result.text,
        citations=[CitationOut(**vars(c)) for c in result.citations],
    )


@app.get("/search", response_model=list[HitOut])
def search(
    q: str = Query(min_length=3),
    ticker: str | None = None,
    year: str | None = None,
    k: int = Query(default=6, ge=1, le=20),
    embedder=Depends(get_embedder),
    collection=Depends(get_chroma),
):
    hits = retrieve(q, k=k, ticker=ticker, year=year, embedder=embedder, collection=collection)
    return [
        HitOut(
            id=h.id,
            score=h.score,
            ticker=h.ticker,
            fiscal_year=h.fiscal_year,
            item=h.item,
            item_title=h.item_title,
            text=h.text,
            source_url=h.source_url,
        )
        for h in hits
    ]
